language: ruby

#cache: bundler

before_install:
  - env
#  - gem update --system
#  - gem update bundler

before_script:
  - bundle exec rake lifespan:db:create

rvm:
  - 2.2
  - ruby-head

gemfile:
  - gemfiles/rails4_0.gemfile
  - gemfiles/rails4_1.gemfile
  - gemfiles/rails4_2.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
